ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS home_texts JSONB DEFAULT '{}'::jsonb;
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS telegram TEXT;
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS tiktok TEXT;
