ALTER TABLE matches 
ADD COLUMN IF NOT EXISTS timer_status TEXT DEFAULT 'stopped',
ADD COLUMN IF NOT EXISTS timer_started_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS elapsed_seconds INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS half_1_duration INTEGER DEFAULT 45,
ADD COLUMN IF NOT EXISTS half_2_duration INTEGER DEFAULT 45,
ADD COLUMN IF NOT EXISTS extra_time_1 INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS extra_time_2 INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS yarimada_lineup JSONB DEFAULT '[]'::jsonb;
