ALTER TABLE matches 
ADD COLUMN IF NOT EXISTS is_hero BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'upcoming',
ADD COLUMN IF NOT EXISTS live_minute TEXT,
ADD COLUMN IF NOT EXISTS added_time TEXT;
