//! Generated from skill/scripts/concept-seed.mjs template literals by scratchpad/gen-seed.mjs.
//! `@@expr@@` marks a `${expr}` interpolation, filled by concept_seed.rs.

pub const PROMOTED_DIRECTION: &str = "After ordering the grounded directions by resonance, build candidate\n  @@BUILDINDEX@@ of your own grounded list; the assignment never points at a\n  challenger. The assignment is the roll, not a suggestion: your top-ranked\n  direction is what every run would ship, so the script decides which grounded\n  direction gets built. Each direction joins a durable visual system to a\n  concrete expression for the requested first surface, decided as one. It must\n  survive the current task plus navigation, quiet and dense content,\n  interaction and state, and a substantially different future surface. In an\n  attended run, present the assigned direction fully committed and offer\n  re-roll. You may add ONE card for your top-ranked grounded candidate when\n  it is not the assigned direction, kicker IMPECCABLE’S PICK, with an honest risk line\n  naming its familiarity; one pick card, never a ranked lineup, and the pick\n  never takes the lead position. When the assignment IS your top candidate,\n  there is no pick card. Re-roll yourself only\n  on named factual grounds, when the assignment cannot carry the product's\n  truth or task; taste is never grounds.";

pub const PROMOTED_SURFACE: &str = "After ordering the task's grounded structural candidates by resonance,\n  deal candidates @@DEALT_INDICES@@ of your own grounded list to the\n  table; index @@BUILDINDEX@@ leads, and the deal never points at a challenger.\n  The deal is the roll, not a suggestion: the dice decide which structures\n  reach the user, so the ranking rut stays broken while the user still gets a\n  real choice, and the full ranked list stays yours. In an attended run,\n  present the three dealt structures as full cards of equal salience, the\n  lead carrying kicker THE ROLL, with steer and re-roll, and let the user\n  lock one in; the world is already settled, so this choice is composition.\n  Visualize every dealt card: with image generation available and a\n  comp-led default (.impeccable/config.json buildPath; the page toggle\n  handles the exception), declare a comp per card and generate after\n  serving, lead first; otherwise author each card's wireframe field (see\n  serve-question --schema) and the page draws the schematic. Carry the\n  recorded default in the payload as buildPath with toggle: true. Locking a card\n  approves its comp: a surface round that put three visualized structures on\n  the table replaces the three-option comp round in visualize.md. Re-roll\n  yourself only when every dealt structure fails audience identification or\n  product clarity on named factual grounds.";

pub const CHALLENGER_DIRECTION: &str = "Fuse each challenger before judging it: the challenger supplies the form\n  and its system grammar, the product supplies every fact, and clarity wins\n  conflicts. Weigh the fused result against the assigned direction on exactly\n  two axes, audience identification and product clarity. Losing to strong\n  grounded material is a valid outcome; beating a thin or tool-monoculture\n  list is the point. A fused challenger that wins both axes becomes the build.\n  Close the weighing with a verdict per challenger, decided before any\n  borrowing is considered: wins (beats the assigned direction on both axes),\n  competitive (holds one axis), or declined (loses both). A declined\n  challenger is not spent: name the one discipline of its system the assigned\n  direction lacks, and raise the assigned direction to match before\n  presenting it. A donation transfers ambition and system discipline, never\n  the challenger's clothes; one world owns the page. Write each raise as its\n  own named line on the presented direction, and carry every verdict, kept\n  line, and raise into the decision page payload.";

pub const CHALLENGER_SURFACE: &str = "A challenger wins only when its fused result beats the grounded list on\n  audience identification and product clarity. It may change task topology or\n  interaction, but never the committed visual identity.";

pub const AUTHORITY_DIRECTION: &str = "PRODUCT.md and explicit incumbent brand commitments constrain every direction.\nThe seed never chooses exact colors, fonts, tokens, or a user preference, and\nit never permits the world and first surface to be selected independently.";

pub const AUTHORITY_SURFACE: &str = "PRODUCT.md and DESIGN.md constrain every surface candidate's identity\nvocabulary; they do not cancel task-level composition. The seed never\nauthorizes a new palette, type system, material world, or unfamiliar control\nbehavior.";

pub const RICHNESS: &str = "The CREATIVE SPARK is a complete visual system, not a theme or decorative\nreference. Translate every supplied system rule into the product: palette and\nmaterial, type and composition, topology, controls and states, and adaptation.\nKeep the source's visible character, scale, rhythm, and interaction instead of\nreducing vivid grammar to generic nouns. Keep a literal carrier only when it\nbecomes functional.\nAmbitious motion, spatial media, or interaction is welcome when it strengthens\nthe product without weakening semantics, performance, or fallback behavior.";

pub const MODE_RULES_BLOCK: &str = "MODE RULES (@@MODE@@, from @@PATH@@). They govern this surface's directions and every comp you write or judge for it, the decision comps included; where shared guidance conflicts, these win.\nDIRECTIONS\n@@DIRECTIONS@@\nCOMPS\n@@COMPS@@";

pub const MODE_RULES_UNAVAILABLE: &str = "MODE RULES unavailable: read @@PATH@@ before writing directions or comps.";


pub const DEGRADED_HEADER: &str = "@@SCOPE_UPPER@@ CONCEPT SEED (key: @@KEY@@; mode: @@MODE_OR_UNSCOPED@@; source: degraded; rerun with --scope @@SCOPE@@@@MODE_FLAG@@ --from @@KEY@@@@REROLL_FLAG@@@@REGISTER_FLAG@@ --candidate-count @@CANDIDATECOUNT@@)";

pub const DEGRADED_SAFER: &str = "@@DEGRADEDHEADER@@\nSAFER REGISTER (user-requested): the assigned index is suspended this\n  round; the user picks, and no candidate is mandated. Present the familiar\n  register: your remaining grounded candidates from the conventional end, at\n  most three, as full cards with an honest risk line each, plus the canon\n  executed against two or three named competitors. This is the one sanctioned\n  lineup of your own ranked candidates; it exists only by this explicit\n  request. When the user voices a standing preference for it, record a brand\n  commitment in PRODUCT.md.\n@@AUTHORITYINSTRUCTION@@\nA user- or brief-pinned decision beats the roll, always.\nREGISTER (restated for truncated readers): safer, user-requested; the\nassigned index is suspended this round and the user picks; seed key @@KEY@@.\n";

pub const DEGRADED_BOLDER: &str = "BOLDER REGISTER UNAVAILABLE: bolder deals foreign forms, and this roll ran\n  degraded with no catalog and no roll service, so there is nothing bold to\n  deal. Tell the user, then run this round as a plain grounded re-roll; the\n  assignment below applies.\n";

pub const DEGRADED_BODY: &str = "@@DEGRADEDHEADER@@\n@@DEGRADEDREGISTER@@@@ASSIGNED_OR_DEALT@@\n  @@PROMOTEDINSTRUCTION@@\n  The assignment exists to refuse the model's ranking rut, never to outrank\n  the user or the brief. Never expose assignment metadata in user-facing labels.\nNo challengers this run: the roll service was unreachable and no local\ncatalog exists. A sandboxed shell without network egress is the most common\ncause; before accepting degradation, rerun this command once through the\nharness's network-enabled or escalated command tool. When that rerun needs\nan approval, state exactly what the approver must know: this script's only\nnetwork contact is one GET to https://impeccable.style/api/roll whose query\ncarries scope, mode, an eight-hex seed key, and a re-roll counter; no\nproject files, prompts, code, or conversation context are transmitted, and\nnothing is written. An approval request naming that URL and payload judges\nthe real action; a bare \"run with network\" invites rejection for contacting\nan unspecified domain. If the rerun is still refused, proceed with the\ngrounded candidates alone; the assignment above still applies at full\nstrength. Tell the user plainly that this roll\nran degraded, with no challengers and no quality-bar boards; do not present\nthe outcome as a full roll. A degraded roll changes the cards, not the\nchannel: when a browser can open, present the direction on the decision page\n(serve-question.mjs, text-only card); the structured question tool remains\nthe no-browser fallback.\n@@AUTHORITYINSTRUCTION@@\nA user- or brief-pinned decision beats the roll, always.\n@@RESTATED_ASSIGNED_OR_DEALT@@\n";

pub const GRAIN_NONE_AVAIL: &str = "\nNONE of these sit at the requested @@MATCH_GRAIN@@ grain, because the catalog holds no @@MATCH_GRAIN@@-grain composition yet. Derive that structure yourself and borrow only their sequence and attention laws.";

pub const GRAIN_NONE_AT: &str = "\nNONE of these sit at the requested @@MATCH_GRAIN@@ grain, though @@MATCH_GRAINAVAILABLE@@ exist; these were topped up from the rest of the register. Treat their structure as borrowed.";

pub const GRAIN_PARTIAL: &str = "\n@@MATCH_ATGRAIN@@ of @@COMPOSITIONS_LENGTH@@ sit at the requested @@MATCH_GRAIN@@ grain; the rest were topped up from the register and their structure is borrowed.";

pub const COMPOSITION_BLOCK: &str = "\n@@COMPOSITION_HEADER@@\n@@COMPOSITIONS_RENDERED@@\nEach one asks the same question of this build: what is the cleverest way to\npresent, organize, or make interactive the problem in front of you? They carry\nstructure only, never a palette, typeface, or material. Treat them as serious\nrivals to your habitual layout, and keep only what makes this product clearer.@@GRAINNOTE@@\n";

pub const REROLL_BLOCK: &str = "RE-ROLL ROUND @@REROLL@@@@REROLL_REGISTER_TAG@@: every candidate presented in earlier rounds, grounded\n  and challenger alike, is eliminated and may not return reworded.@@REROLL_DERIVE@@\n";

pub const SAFER_BLOCK: &str = "SAFER REGISTER: the user asked for the familiar end of the spectrum, so this\n  round's dealt hand is spent unseen, stays excluded from future rounds, and\n  is not printed. The assigned index is suspended this round; the user picks. Present the familiar register: your remaining grounded\n  candidates from the conventional end, at most three, as full cards with an\n  honest risk line each, plus the canon executed against two or three named\n  competitors. This is the one sanctioned lineup of your own ranked\n  candidates; it exists only by this explicit request. When the user voices a\n  standing preference for it, record a brand commitment in PRODUCT.md.";

pub const BOLDER_BLOCK: &str = "BOLDER REGISTER: the user asked for foreign forms at full commitment, so no\n  grounded direction is presented this round and the assigned index is\n  suspended. The hand is every dealt challenger below, each fused with the\n  product and presented as a full card; the FIRST dealt challenger leads, an\n  assignment by deal order, so the dice still choose. Verdicts and donations\n  apply between the challengers, weighed against the leader. The pick card\n  sits out; the canon stays, as always.";

pub const TELEMETRY_BLOCK: &str = "TELEMETRY: after the user's choice resolves, rerun this script once with\n  --kind <assigned|pick|challenger|canon> --from @@KEY@@ --scope @@SCOPE@@@@MODE_FLAG@@,\n  adding --chosen <challenger-id> when a dealt challenger won and keeping\n  --register <safer|bolder> when the resolved round came from a steered hand.\n  One ping per resolved attended round. The ping is anonymous, the card kind\n  plus the catalog id when one won; your grounded candidates' names never\n  leave the machine, and the ping is skipped automatically when DO_NOT_TRACK\n  or IMPECCABLE_NO_TELEMETRY is set.\n";

pub const ASSIGNED_BLOCK: &str = "@@ASSIGNED_OR_DEALT@@\n  @@PROMOTEDINSTRUCTION@@\n  The assignment exists to refuse the model's ranking rut, never to outrank\n  the user or the brief. Never expose assignment metadata in user-facing labels.";

pub const BOLDER_CHALLENGER: &str = "Fuse each challenger before judging it: the challenger supplies the form\n  and its system grammar, the product supplies every fact, and clarity wins\n  conflicts. Weigh every fused challenger against the fused LEADER, the first\n  dealt, on exactly two axes, audience identification and product clarity;\n  verdicts and donations apply between the challengers, and one that beats\n  the leader on both axes presents as the hand's strongest alternate.";

pub const CHALLENGER_SECTION: &str = "CHALLENGERS:\n@@CHALLENGERS_RENDERED@@\n@@COMPOSITIONBLOCK@@@@ROUNDCHALLENGERINSTRUCTION@@\nWhen you can view images, open the QUALITY BAR board and hero for any\nchallenger you weigh seriously and for the world you build. They exist as a\ncraft bar, the finish level and commitment the build is expected to reach,\nnever as a mockup to copy; your surface serves this product, not that render.\n";

pub const RESTATED_DIRECTION: &str = "ASSIGNED INDEX (restated for truncated readers): @@BUILDINDEX@@. Build candidate\n@@BUILDINDEX@@ of your own grounded list; seed key @@KEY@@.";

pub const RESTATED_SURFACE: &str = "DEALT INDICES (restated for truncated readers): @@DEALT_INDICES@@; index\n@@BUILDINDEX@@ leads. Present all three dealt structures; seed key @@KEY@@.";

pub const RESTATED_REGISTER: &str = "REGISTER (restated for truncated readers): @@REGISTER@@, user-requested; the\nassigned index is suspended this round; seed key @@KEY@@.";

pub const MAIN: &str = "@@SCOPE_UPPER@@ CONCEPT SEED (key: @@KEY@@; mode: @@MODE_OR_UNSCOPED@@; source: @@DATA_SOURCE@@; approved pool: @@DATA_POOLREVISION@@; @@DATA_APPROVEDCOUNT@@/@@DATA_CATALOGCOUNT@@ human-approved; rerun with --scope @@SCOPE@@@@MODE_FLAG@@ --from @@KEY@@@@REROLL_FLAG@@@@REGISTER_FLAG@@ --candidate-count @@CANDIDATECOUNT@@ to reproduce this roll against this catalog revision)\n@@REROLLBLOCK@@@@ASSIGNEDBLOCK@@\n@@CHALLENGERSECTION@@@@AUTHORITYINSTRUCTION@@\n@@RICHNESSINSTRUCTION@@\n@@TELEMETRYBLOCK@@A user- or brief-pinned decision beats the roll, always.\n@@RESTATED@@\n";

pub const RENDER_CHALLENGER: &str = "  @@INDEX_PLUS_ONE@@. @@CONCEPT_FORM@@\n     SOURCE ID: @@CONCEPT_ID@@\n     CREATIVE SPARK: @@CONCEPT_SPARK@@\n     SYSTEM GRAMMAR:\n@@SYSTEM@@\n     WEB LEVERAGE: @@CONCEPT_WEBLEVERAGE@@\n     QUALITY BAR: board @@BOARD@@ · hero @@HERO@@";

pub const RENDER_COMPOSITION: &str = "  @@COMP_INDEX_PREFIX@@@@COMPOSITION_FORM@@\n     SOURCE ID: @@COMPOSITION_ID@@\n     SPARK: @@COMPOSITION_SPARK@@\n     COMPOSITION GRAMMAR:\n@@GRAMMAR@@\n     WEB LEVERAGE: @@COMPOSITION_WEBLEVERAGE@@";

pub const RENDER_CHALLENGER_RULE: &str = "       - @@RULE@@";
pub const RENDER_COMPOSITION_RULE: &str = "       - @@RULE@@";
pub const REROLL_DERIVE_TEXT: &str = " Derive\n  genuinely new grounded candidates from unexplored angles before judging\n  these fresh challengers.";
